[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 600
unfocused_hollow = true

[window]
padding = { x = 0, y = 0}
dynamic_padding = true

[font]
size = 10.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"
